# Commands to start on workspace startup
tasks:
  - name: "Prepare Environment"
    init: > 
      poetry install &&
      gp sync-done install
  - name: "Activate the shell"
    init: gp sync-await install
    command: poetry shell
  - name: "Beerlog"
    command: beerlog

# Ports to expose on workspace startup
# ports:
#   - port: 8000
#     onOpen: open-preview
#     visibility: public

vscode:
  extensions:
    - "ms-python.python@2021.9.1218897484"
    - "redhat.vscode-yaml"
    - "tamasfe.even-better-toml"
    - "alexcvzz.vscode-sqlite"
    - "jdinhlife.gruvbox"

image:
  file: .gitpod.Dockerfile